#:import QReaderApp utils.reader.QReader

<ReaderScreen>:
    QReader:
        id: reader

<GeneratorScreen>:
    Button:
        text: "This is dummy second window button"

<WindowManager>:
    id: windowManager



    GeneratorScreen:
        id: generatorScreen
        name: "generatorScreen"
        manager: windowManager

    ReaderScreen:
        id: readerWindow
        name: "readerScreen"
        manager: windowManager
